# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "crypt"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan Langevin"]
  s.date = "2011-10-22"
  s.description = "Fixes several small bugs relating to string encoding"
  s.email = "dan.langevin@lifebooker.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "crypt.gemspec",
    "crypt.txt",
    "lib/crypt.rb",
    "lib/crypt/blowfish-tables.rb",
    "lib/crypt/blowfish.rb",
    "lib/crypt/cbc.rb",
    "lib/crypt/gost.rb",
    "lib/crypt/idea.rb",
    "lib/crypt/noise.rb",
    "lib/crypt/purerubystringio.rb",
    "lib/crypt/rijndael-tables.rb",
    "lib/crypt/rijndael.rb",
    "lib/crypt/stringxor.rb",
    "plain.txt",
    "test/helper.rb",
    "test/test-blowfish.rb",
    "test/test-gost.rb",
    "test/test-idea.rb",
    "test/test-rijndael.rb",
    "test/ts_crypt.rb"
  ]
  s.homepage = "http://github.com/dlangevin/crypt"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Crypt for Ruby 1.9"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
  end
end

